version: "3.5"
services:
  develop:
    build: .
    ports:
      - "4401:4401"
    container_name: fw-forms-develop
    environment:
      PORT: 4401
      NODE_ENV: dev
      SUPPRESS_NO_CONFIG_WARNING: "true"
      MONGO_PORT_27017_TCP_ADDR: mongo
      DB_SECRET: '{ "username": "admin", "password": "password" }'
      DB_DATABASE: gfw_forms
      CT_URL: https://staging-api.resourcewatch.org
      LOCAL_URL: http://127.0.0.1:4401
      TEAMS_API_URL: http://fw-teams-develop:3035/api/v1
      V3_TEAMS_API_URL: https://dev-fw-api.globalforestwatch.org/v3
      AREAS_API_URL: https://api.resourcewatch.org
      API_API_URL: https://dev-fw-api.globalforestwatch.org/v3/forest-watcher
      WRI_MAIL_RECIPIENTS: <mails>
      TARGET_SHEET_ID: <sheet>
      S3_ACCESS_KEY_ID: <key>
      S3_SECRET_ACCESS_KEY: <key>
      S3_BUCKET: <key>
      MICROSERVICE_TOKEN: ${microservice_token}
    volumes:
      - ./app:/opt/gfw-forms-api/app
      - ./nodemon.json:/opt/gfw-forms-api/nodemon.json
    command: yarn dev
    depends_on:
      - mongo
    networks:
      - gfw-forms-network
      - gfw-network

  docs:
    build: .
    ports:
      - "44010:44010"
    container_name: fw-forms-docs
    volumes:
      - ./docs:/opt/gfw-forms-api/docs
    command: yarn run docs -l 44010

  mongo:
    image: mongo:3.4
    container_name: gfw-forms-mongo
    ports:
      - "27024:27017"
    environment:
      MONGO_INITDB_DATABASE: gfw_forms
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: admin
    volumes:
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - gfw-forms-mongodb-data:/data/db
    restart: always
    networks:
      - gfw-forms-network

  test:
    build: .
    container_name: fw-forms-test
    environment:
      PORT: 0
      NODE_ENV: test
      SUPPRESS_NO_CONFIG_WARNING: "true"
      MONGO_PORT_27017_TCP_ADDR: mongo
      DB_SECRET: '{ "username": "admin", "password": "password" }'
      DB_DATABASE: gfw_forms
      CT_URL: http://127.0.0.1:9000
      LOCAL_URL: http://127.0.0.1:4400
      TEAMS_API_URL: http://127.0.0.1:9000
      AREAS_API_URL: http://127.0.0.1:9000
      API_API_URL: http://127.0.0.1:9000/v3/forest-watcher
      V3_TEAMS_API_URL: http://127.0.0.1:9000/v3
      WRI_MAIL_RECIPIENTS: <mails>
      TARGET_SHEET_ID: <sheet>
      S3_ACCESS_KEY_ID: <key>
      S3_SECRET_ACCESS_KEY: <key>
      S3_BUCKET: <key>
      MICROSERVICE_TOKEN: ${microservice_token}
    volumes:
      - ./app:/opt/gfw-forms-api/app
      - ./nodemon.json:/opt/gfw-forms-api/nodemon.json
      - ./jest.config.js:/opt/gfw-forms-api/jest.config.js
    command: yarn test:jest --runInBand
    depends_on:
      - mongo
    networks:
      - gfw-forms-network
      - gfw-network

volumes:
  gfw-forms-mongodb-data:

networks:
  gfw-forms-network:
    name: gfw-forms-network
  gfw-network:
    name: gfw-network
