version: "3"
services:
  test:
    build: .
    ports:
      - "4400:4400"
    container_name: fw-forms-test
    environment:
      PORT: 4400
      NODE_PATH: app/src
      NODE_ENV: test
      SUPPRESS_NO_CONFIG_WARNING: "true"
      MONGO_PORT_27017_TCP_ADDR: mongo
      DB_SECRET: '{ "username": "admin", "password": "password" }'
      DB_DATABASE: gfw_forms
      CT_URL: http://127.0.0.1:9000
      LOCAL_URL: http://127.0.0.1:4400
      TEAMS_API_URL: http://127.0.0.1:9000
      AREAS_API_URL: http://127.0.0.1:9000
      WRI_MAIL_RECIPIENTS: <mails>
      TARGET_SHEET_ID: <sheet>
      S3_ACCESS_KEY_ID: <key>
      S3_SECRET_ACCESS_KEY: <key>
      S3_BUCKET: <key>
    depends_on:
      - mongo
    command: node node_modules/.bin/grunt --gruntfile app/Gruntfile.js e2eTest

  mongo:
    image: mongo:3.4
    command: --smallfiles
    ports:
      - "27017"
    environment:
      MONGO_INITDB_DATABASE: gfw_forms
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_ROOT_USERNAME: admin
    volumes:
      - ./data/mongo/001_users.js:/docker-entrypoint-initdb.d/001_users.js:ro
      - gfw-forms-mongodb-data:/data/db

volumes:
  gfw-forms-mongodb-data:
