version: "3.5"
services:
  develop:
    build: .
    ports:
      - "4401:4401"
    container_name: fw-forms-develop
    environment:
      PORT: 4401
      NODE_PATH: app/src
      NODE_ENV: dev
      SUPPRESS_NO_CONFIG_WARNING: "true"
      MONGO_PORT_27017_TCP_ADDR: mongo
      CONTROL_TOWER_URL: https://api.resourcewatch.org
      LOCAL_URL: http://127.0.0.1:4401
      TEAMS_API_URL: http://fw-teams-develop:3035/api/v1
      AREAS_API_URL: https://api.resourcewatch.org
      WRI_MAIL_RECIPIENTS: <mails>
      TARGET_SHEET_ID: <sheet>
      S3_ACCESS_KEY_ID: <key>
      S3_SECRET_ACCESS_KEY: <key>
      S3_BUCKET: <key>
    volumes:
      - ./app:/opt/gfw-forms-api/app
    depends_on:
      - mongo
    networks:
      - gfw-forms-network
      - gfw-network
    command: node node_modules/.bin/grunt --gruntfile app/Gruntfile.js

  mongo:
    image: mongo:3.4
    container_name: gfw-forms-mongo
    ports:
      - "27024:27017"
    volumes:
      - $HOME/docker/data/gfw-forms-api/mongodb:/data/db
    restart: always
    networks:
      - gfw-forms-network

networks:
  gfw-forms-network:
    name: gfw-forms-network
  gfw-network:
    name: gfw-network
